### ISSUE TITLE
: Configure SSO for Grafana.

### ISSUE THREAD

**Issue by SonOfLope** [ai-cfia/howard#64]
As part of our Epic to manage access to our system apps part of our cluster, we would like to be able to authenticate users to grafana through our Github organisation.

**Comment by rngadam** [comment]
@SonOfLope no Projects set?

**Comment by SonOfLope** [comment]
Done in https://github.com/ai-cfia/howard/pull/89

**Comment by rngadam** [comment]
@SonOfLope I noticed there is no "fixes #" in the commits or PR desdcription so this issue remains open even though the PR has been merged:

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

in the future, I suggest adding a "fixes issue #" into the description of the PR.
